language: rust
install:
  - sudo apt-get install libXxf86vm-dev
  - sudo apt-get install libsfml-dev
  - sudo apt-get install libjpeg62
  - sudo apt-get update
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.0.3
  - cmake -DBUILD_SHARED_LIBS=ON
  - make
  - sudo make install
  - cd ..
  - wget http://www.sfml-dev.org/download/sfml/2.1/SFML-2.1-linux-gcc-64bits.tar.bz2
  - tar xf SFML-2.1-linux-gcc-64bits.tar.bz2
  - sudo cp -r SFML-2.1/lib/* /usr/local/lib/.
  - wget http://www.sfml-dev.org/download/csfml/CSFML-2.1-linux-gcc-64bits.tar.bz2
  - tar xf CSFML-2.1-linux-gcc-64bits.tar.bz2
  - sudo cp -r CSFML-2.1/lib/* /usr/local/lib/.
