sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
env:
  - TARGET="x86_64-unknown-linux-gnu" SUBCOMMAND=""
  - TARGET="wasm32-unknown-unknown" SUBCOMMAND="web"
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
script:
  - if [ "$SUBCOMMAND" == "web" ]; then cargo install -f cargo-web; fi
  - cargo ${SUBCOMMAND} build --target ${TARGET} -p nphysics2d
  - cargo ${SUBCOMMAND} build --target ${TARGET} -p nphysics3d
  - cargo ${SUBCOMMAND} build --target ${TARGET} -p nphysics_testbed2d
  - cargo ${SUBCOMMAND} build --target ${TARGET} -p nphysics_testbed3d
  - cargo ${SUBCOMMAND} build --target ${TARGET} -p nphysics-examples-2d
  - cargo ${SUBCOMMAND} build --target ${TARGET} -p nphysics-examples-3d
  - cargo ${SUBCOMMAND} test --target ${TARGET} -p nphysics2d
  - cargo ${SUBCOMMAND} test --target ${TARGET} -p nphysics3d
  - cargo ${SUBCOMMAND} test --target ${TARGET} -p nphysics_testbed2d
  - cargo ${SUBCOMMAND} test --target ${TARGET} -p nphysics_testbed3d
  - cargo ${SUBCOMMAND} test --target ${TARGET} -p nphysics-examples-2d
  - cargo ${SUBCOMMAND} test --target ${TARGET} -p nphysics-examples-3d
