[package]
name    = "nphysics"
version = "0.1.0"
authors = [ "SÃ©bastien Crozet <developer@crozet.re>" ]

description = "2 and 3-dimensional physics engine in Rust."
documentation = "http://nphysics-dev.org/doc/nphysics"
homepage = "http://nphysics-dev.org"
repository = "https://github.com/sebcrozet/nphysics"
readme = "README.md"
keywords = [ "physics", "dynamics", "rigid", "real-time", "joints" ]
license = "BSD-3-Clause"

[features]
f32 = [ ]
f64 = [ ]
2d  = [ ]
3d  = [ ]
4d  = [ ]

2df32 = [ "2d", "f32" ]
2df64 = [ "2d", "f64" ]
3df32 = [ "3d", "f32" ]
3df64 = [ "3d", "f64" ]
4df32 = [ "4d", "f32" ]
4df64 = [ "4d", "f64" ]

[lib]
name = "nphysics"
path = "src/lib.rs"

[dependencies.ncollide]
git = "https://github.com/sebcrozet/ncollide"
