[package]
name    = "nphysics_testbed3d"
version = "0.1.0"
authors = [ "SÃ©bastien Crozet <developer@crozet.re>" ]

[lib]
name = "nphysics_testbed3d"

[dependencies.nphysics]
features = [ "3df32" ]
path = "../.."

[dependencies.time]
git = "https://github.com/rust-lang/time"
 
[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.ncollide]
git = "https://github.com/sebcrozet/ncollide"

[dependencies.kiss3d]
git = "https://github.com/sebcrozet/kiss3d"
