[package]
name    = "nphysics_testbed3d"
version = "0.1.0"
authors = [ "SÃ©bastien Crozet <developer@crozet.re>" ]

[lib]
name = "nphysics_testbed3d"

[dependencies]
num-traits = "0.1"
time       = "0.1"
rand       = "0.4"
glfw       = "0.19"
nalgebra   = "0.14"
kiss3d     = "0.13"
ncollide3d = { path = "../../ncollide-dev/build/ncollide3d" }

[dependencies.nphysics3d]
path = "../build/nphysics3d"
