[package]
name    = "nphysics_testbed2d"
version = "0.1.0"
authors = [ "SÃ©bastien Crozet <developer@crozet.re>" ]

[lib]
name = "nphysics_testbed2d"

[dependencies.nphysics2d]
path = "../build/nphysics2d"

[dependencies]
sfml       = "0.11"
time       = "0.1"
num-traits = "0.1"
rand       = "0.4"
nalgebra   = "0.14"
ncollide   = "0.14"
